import os
import time
import ray
import lance
import pyarrow as pa
from ray import serve
from starlette.requests import Request
from typing import List

# This file is generated by your protoc compiler
import user_data_pb2

# Configuration - Change this to your actual S3 bucket
S3_LANCE_PATH = os.environ.get("S3_LANCE_PATH", "s3://yashwant-test/linkedin_profiles.lance")
storage_options = {
    "aws_access_key_id": os.environ["AWS_ACCESS_KEY_ID"],
    "aws_secret_access_key": os.environ["AWS_SECRET_ACCESS_KEY"],
    "region": os.environ.get("AWS_REGION", "us-east-2"),
}

@serve.deployment(num_replicas=1)
class BatchedEnricher:
    """
    Handles the heavy lifting (LLM/Processing) and 
    commits the results to the Lance dataset on S3.
    """
    @serve.batch(max_batch_size=5, batch_wait_timeout_s=0.5)
    async def handle_batch(self, user_list: List[dict]):
        print(f"--- Processing Batch of {len(user_list)} ---")
        
        # 1. Simulated LLM Latency
        time.sleep(0.5) 
        
        # 2. Enrich the data
        enriched_results = []
        for u in user_list:
            enriched_results.append({
                "id": u["id"],
                "name": u["name"],
                "location": u["location"],
                "summary": f"Enriched {u['name']} from {u['location']}",
                "status": "success",
                "timestamp": time.time()
            })

        # 3. CONVERGENT STEP: Write to Lance on S3
        # We convert the list of dicts to a PyArrow table for Lance
        table = pa.Table.from_pylist(enriched_results)
        
        # Mode='append' creates new 'Fragments' in S3, which is very efficient
        lance.write_dataset(table, S3_LANCE_PATH, mode="append", storage_options=storage_options)
        
        return enriched_results

    async def enrich(self, user_info: dict):
        return await self.handle_batch(user_info)

@serve.deployment
class ProtobufIngress:
    """
    The Entry Point: Receives Protobuf via HTTP and 
    forwards it to the BatchedEnricher.
    """
    def __init__(self, enricher_handle):
        self.enricher_handle = enricher_handle

    async def __call__(self, http_request: Request):
        # 1. Receive Binary Protobuf
        proto_bytes = await http_request.body()
        user = user_data_pb2.UserData()
        user.ParseFromString(proto_bytes)
        
        # 2. Convert to dict for the worker
        user_dict = {
            "id": user.id, 
            "name": user.name, 
            "location": user.location
        }
        
        # 3. Call the batched enricher (this will wait for a batch of 5)
        result = await self.enricher_handle.enrich.remote(user_dict)
        return result

# Bind the deployments together
app = ProtobufIngress.bind(BatchedEnricher.bind())