# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_data.proto\":\n\x07Profile\x12\x11\n\tmember_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06skills\x18\x03 \x01(\t\"*\n\x0cProfileBatch\x12\x1a\n\x08profiles\x18\x01 \x03(\x0b\x32\x08.Profile\"E\n\rGithubProfile\x12\x17\n\x0fgithub_username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05repos\x18\x03 \x01(\t\"6\n\x12GithubProfileBatch\x12 \n\x08profiles\x18\x01 \x03(\x0b\x32\x0e.GithubProfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE']._serialized_start=19
  _globals['_PROFILE']._serialized_end=77
  _globals['_PROFILEBATCH']._serialized_start=79
  _globals['_PROFILEBATCH']._serialized_end=121
  _globals['_GITHUBPROFILE']._serialized_start=123
  _globals['_GITHUBPROFILE']._serialized_end=192
  _globals['_GITHUBPROFILEBATCH']._serialized_start=194
  _globals['_GITHUBPROFILEBATCH']._serialized_end=248
# @@protoc_insertion_point(module_scope)
